apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsonplaceholder
spec:
  ingressClassName: ingress-http.gateway
  rules:
  - http:
      paths:
      - path: /api(/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: paymentsservice
            port:
              number: 80