---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: payments
spec:
  ports:
  - name: http
    targetPort: 3000
    port: 3000
  selector:
    app: payments
    microservice: app