apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-ingress
spec:
  ingressClassName: ingress-http.gateway
  rules:
  - http:
      paths:
      - path: /ms(/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: payments-service
            port:
              number: 3000